name: CD

on: 
  push:
    branches:    
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: install
      run: npm i
    - name: Build SASS
      run: gulp styles
    - name: Bundle
      run: mkdir ./out && mkdir ./out/uber-partners && cp -r src/css src/fonts src/img src/icons src/js ./out/uber-partners/ && cp src/index.html ./out/uber-partners/
      
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.DEPLOY_TOKEN }}
        external_repository: MemboLembo/MemboLembo.github.io
        publish_dir: ./out
        publish_branch: master
        keep_files: true
